name: 'Terraform'
on:
  pull_request:
  push:
    branches:
      - main 

jobs:
  terraform-initialize:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
        - uses: action/checkout@v2
        - uses: hashicorp/setup-terraform@v1
        
          
