name: 'terraform'
on:
  push:
    branches:
      - main 

jobs:
  terraform-initialize:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: terraform-setup
      uses: hashicorp/setup-terraform@v1
      with: cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
    - name: terraform Format
        id: fmt
        run: terraform fmt -check
    
    - name: terraform-init
        id: init
        run: terraform init
      
    - name: terraform-validate
        id: validate
        run: terraform validate -no-color

    - name: terraform-plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true
